version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - MYSQL_SERVER=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DB=event_management
      - MYSQL_PORT=3306
    depends_on:
      - db
    volumes:
      - .:/app

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=event_management
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data:
